TrajectoryPlannerROS:
  max_vel_x: 0.8 #0.45
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4

  acc_lim_theta: 2.0 #3.2
  acc_lim_x: 0.5 #2.5
  acc_lim_y: 0 #2.5

  holonomic_robot: false

  meter_scoring: true
