idmind_robot:
  robot: "omni"
  kinematics: "omnidirectional"
  wheels: 4
  wheel_radius: 0.05
  base_width: 0.319 #equivalent = a + b
  max_acc_v: 0.2
  max_acc_w: 0.5
  acc_dec_factor: 6.0
  max_v: 0.6
  max_w: 1.0
  velocity_offset: 0

  ticks: 27592

  encoders_command: 0x4A
  velocity_command: 0x56
  voltages_command: 0x51



