obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.347,0.287],[0.347,-0.287],[-0.323,-0.287],[-0.323,0.287]]
#robot_radius: ir_of_robot
inflation_radius: 0.6 #0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

map_type: costmap
