TrajectoryPlannerROS:
  max_vel_x: 0.6 #0.45
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4

  acc_lim_theta: 0.5 #3.2
  acc_lim_x: 0.2 #2.5
  acc_lim_y: 0.2 #2.5

  holonomic_robot: true

  meter_scoring: true

  pdist_scale: 1.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.04 #0.01

  latch_xy_goal_tolerance: true
